import { createTranslator } from "@/locales"
import { getCurrentLocale } from "@/locales/config"

const cache = new Map<string, string>()
const MAX_CACHE_SIZE = 500

/**
 * translateDisplayTitle
 *
 * Translates the displayTitle string generated by the Go backend into current locale.
 * The backend always generates these strings in English (e.g. "Episode 7", "Special 2"),
 * so we intercept them here in the frontend to keep ALL translations in the /locales folder
 * and avoid modifying the backend — which would cause merge conflicts on upstream updates.
 *
 * Patterns handled:
 *  "Episode N & X more"  → "Episodio N y X más"
 *  "Episode N - Title"   → "Episodio N - Title" (defensivo, FilePreview/futuro)
 *  "Episode N"           → "Episodio N"
 *  "Special N - Title"   → "Especial N - Title"
 *  "Special N"           → "Especial N"
 *  Everything else (movie titles, NC titles, etc.) → returned as-is
 */
export function translateDisplayTitle(displayTitle: string | undefined | null): string {
    if (!displayTitle) return ""
    const cacheKey = `${getCurrentLocale()}:${displayTitle}`
    const cached = cache.get(cacheKey)
    if (cached !== undefined) return cached

    const t = createTranslator()
    const normalize = (n: string) => String(parseInt(n, 10) || n)

    const store = (res: string) => {
        if (cache.size >= MAX_CACHE_SIZE) cache.clear()
        cache.set(cacheKey, res)
        return res
    }

    // "Episode 6 & 4 more" → must be before generic Episode
    const moreMatch = displayTitle.match(/^Episode (\d+) & (\d+) more$/)
    if (moreMatch) {
        return store(t("common.labels.episodeNumberAndMore", { number: normalize(moreMatch[1]), count: moreMatch[2] }))
    }

    // "Episode 7 - Title" defensivo (FilePreview y futuro-proof)
    const epWithTitle = displayTitle.match(/^Episode (\d+)\s*-\s*(.+)$/)
    if (epWithTitle) {
        return store(`${t("common.labels.episodeNumber", { number: normalize(epWithTitle[1]) })} - ${epWithTitle[2]}`)
    }

    // "Episode 7" → zero-pad normalizado "07" => "7"
    const episodeMatch = displayTitle.match(/^Episode (\d+)$/)
    if (episodeMatch) {
        return store(t("common.labels.episodeNumber", { number: normalize(episodeMatch[1]) }))
    }

    // "Special 2 - Title" defensivo
    const specialWithTitle = displayTitle.match(/^Special (\S+)\s*-\s*(.+)$/)
    if (specialWithTitle) {
        return store(`${t("common.labels.specialEpisodeNumber", { number: specialWithTitle[1] })} - ${specialWithTitle[2]}`)
    }

    // "Special 2" → "Especial 2"
    const specialMatch = displayTitle.match(/^Special (\S+)$/)
    if (specialMatch) {
        return store(t("common.labels.specialEpisodeNumber", { number: specialMatch[1] }))
    }

    return store(displayTitle)
}
