/**
 * translateDisplayTitle
 *
 * Translates the displayTitle string generated by the Go backend into Spanish.
 * The backend always generates these strings in English (e.g. "Episode 7", "Special 2"),
 * so we intercept them here in the frontend to keep ALL translations in the /locales folder
 * and avoid modifying the backend — which would cause merge conflicts on upstream updates.
 *
 * Patterns handled:
 *  "Episode N"  → "Episodio N"
 *  "Special N"  → "Especial N"
 *  Everything else (movie titles, NC titles, etc.) → returned as-is
 */
export function translateDisplayTitle(displayTitle: string | undefined | null): string {
    if (!displayTitle) return ""

    // "Episode 7" → "Episodio 7"
    const episodeMatch = displayTitle.match(/^Episode (\d+)$/)
    if (episodeMatch) {
        return `Episodio ${episodeMatch[1]}`
    }

    // "Special 2" → "Especial 2"
    const specialMatch = displayTitle.match(/^Special (\S+)$/)
    if (specialMatch) {
        return `Especial ${specialMatch[1]}`
    }

    return displayTitle
}
